preload = /home/thomasdevasia/Pictures/100-wall.jpg
preload = /home/thomasdevasia/Pictures/100-wall.jpg

wallpaper = eDP-1, /home/thomasdevasia/Pictures/100-wall.jpg
wallpaper = HDMI-A-1, /home/thomasdevasia/Pictures/100-wall.jpg
