preload = /home/thomasdevasia/Pictures/whiterabbitdrac.png
preload = /home/thomasdevasia/Pictures/whiterabbitdrac.png

wallpaper = eDP-1, /home/thomasdevasia/Pictures/whiterabbitdrac.png
wallpaper = HDMI-A-1, /home/thomasdevasia/Pictures/whiterabbitdrac.png
