#!/usr/bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# AutoStart applications
sxhkd &
# start compositor
# picom --config $HOME/.config/picom/picom.conf &
# while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom -b --experimental-backends --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
# polybar &
bash ~/.config/polybar/launch.sh --shades &
vmware-user-suid-wrapper &
# for keybord
setxkbmap us &
# for cursor
xsetroot -cursor_name left_ptr &
